site_name: magicgui
# strict: true

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: light-green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - Widgets: widgets/
  - Bases: bases/
  - protocols.md
  - app.md
  - widget_overview.md
  - type_map.md

hooks:
  - docs/_hooks.py

watch:
  - src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - attr_list
  - md_in_html

plugins:
  - search
  - literate-nav
  - autorefs
  - mkdocstrings:
      handlers:
        widget_handler:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_bases: true
            docstring_section_style: list
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://psygnal.readthedocs.io/en/latest/objects.inv
            - https://pint.readthedocs.io/en/stable/objects.inv
          options:
            docstring_style: numpy
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            show_root_full_path: false
            # show_source: false
            show_bases: true
            docstring_section_style: list
  - gen-files:
      scripts:
        - docs/_gen_widgets.py

extra_css:
  - stylesheets/extra.css
