site_name: magicgui
site_url: https://pyapp-kit.github.io/magicgui
site_description: Type-based GUI creation for Python
repo_name: pyapp-kit/magicgui
repo_url: https://github.com/pyapp-kit/magicgui
edit_uri: edit/main/docs/
# strict: true

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: light-green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate

nav:
  - Overview: index.md
  - widgets_overview.md
  - type_map.md
  - events.md
  - decorators.md
  - API:
      - api/magicgui.md
      - api/magic_factory.md
      - widgets: api/widgets/
      - widgets.bases: api/widgets/bases/
      - widgets.protocols: api/protocols.md
      - type_map: api/type_map.md
      - application: api/app.md

hooks:
  - docs/scripts/_hooks.py

watch:
  - src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.extra
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - literate-nav
  - autorefs
  - mkdocstrings:
      handlers:
        widget_handler:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_bases: true
            docstring_section_style: list
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://psygnal.readthedocs.io/en/latest/objects.inv
            - https://pint.readthedocs.io/en/stable/objects.inv
            - https://napari.org/stable/objects.inv
          options:
            docstring_style: numpy
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            show_root_full_path: false
            # show_source: false
            show_bases: true
            docstring_section_style: list
  - gen-files:
      scripts:
        - docs/scripts/_gen_widgets.py
        - docs/scripts/_gen_screenshots.py

extra_css:
  - stylesheets/extra.css
  - stylesheets/pygments.css
