# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.5.2.dev30+ga5e272f.d20220824"
__version_tuple__ = version_tuple = (0, 5, 2, "dev30", "ga5e272f.d20220824")
