#######################################################################################
# Book settings
title: "magicgui" # The title of the book. Will be placed in the left navbar.
logo: images/logo.svg # A path to the book logo
author: Talley Lambert # The author of the book
email: talley.lambert@gmail.com
copyright: "2020" # Copyright year to be placed in the footer

# Execution settings
execute:
  execute_notebooks: cache  # or 'force'
  exclude_patterns:
    - 'README.md'

only_build_toc_files: true

# html:
#   favicon: images/favicon.ico
#   google_analytics_id: UA-xxxxxxxx-x
#   home_page_in_navbar: false
#   use_edit_page_button: true
#   use_repository_button: true
#   use_issues_button: true
#   # baseurl: https://jupyterbook.org/

repository:
  url: https://github.com/napari/magicgui
  branch: master
  path_to_book: docs

# launch_buttons:
#   notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
#   binderhub_url: "https://mybinder.org"
#   colab_url: "https://colab.research.google.com"
#   thebe: true

sphinx:
  local_extensions:
    - ../magicgui

  extra_extensions:
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx.ext.autodoc
    - sphinx_autodoc_typehints
    - sphinx.ext.autosummary

  config:
    # set_type_checking_flag: True  # don't yet know how to add to path with jupyter-book
    autosummary_generate: True
    autosummary_imported_members: True
    # autodoc_typehints: signature
    autodoc_default_options:
        special-members: False
        undoc-members: True
        show-inheritance: True
    # add_module_names: False
    exclude_patterns:
      - README.md
    templates_path:
      - "_templates"
    html_show_sourcelink: False
    html_static_path:
      - "_static"
    html_style: styles.css
    pygments_style: "default"

    intersphinx_mapping:
      python:
        - "https://docs.python.org/3"
        - null

    html_theme: "sphinx_material"
    html_theme_options:
      base_url: "http://magicgui.readthedocs.io/" # Specify a base_url used to generate sitemap.xml links
      repo_url: "https://github.com/napari/magicgui/"
      repo_name: "napari/magicgui"
      # google_analytics_account: "UA-XXXXX"
      # html_minify: True
      # html_prettify: True
      # css_minify: True
      # logo_icon: "&#xe3e4"
      repo_type: "github"
      globaltoc_depth: 2
      # Color Options: red, pink, purple, deep-purple, indigo, blue,
      # light-blue, cyan, teal, green, light-green, lime, yellow,
      # amber, orange, deep-orange, brown, grey, blue-grey, and white.
      color_primary: dark-blue
      color_accent: "cyan"
      # touch_icon: "images/apple-icon-152x152.png"
      theme_color: "#2196f3"
      master_doc: False
      # version_dropdown: True,
    html_sidebars:
      "**":
        - globaltoc.html
        - logo-text.html
        - localtoc.html
        - searchbox.html
